"""third_try

Revision ID: 46887ba7b4d2
Revises: b8c7e4715ccd
Create Date: 2023-04-30 18:26:46.234303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46887ba7b4d2'
down_revision = 'b8c7e4715ccd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'teleg_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drivers', 'teleg_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
