"""6th try

Revision ID: 7f2f58ca0f14
Revises: bb6a856fd449
Create Date: 2023-05-01 18:00:54.819854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f2f58ca0f14'
down_revision = 'bb6a856fd449'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('driver_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'drivers', ['driver_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'driver_id')
    # ### end Alembic commands ###
