"""4th try

Revision ID: 8a75d8188eee
Revises: 46887ba7b4d2
Create Date: 2023-05-01 16:09:05.435864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a75d8188eee'
down_revision = '46887ba7b4d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('car_id', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('car_category', sa.ARRAY(sa.String()), nullable=False))
    op.create_unique_constraint(None, 'drivers', ['car_id'])
    op.create_unique_constraint(None, 'drivers', ['teleg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'car_category')
    op.drop_column('drivers', 'car_id')
    # ### end Alembic commands ###
