"""second_try

Revision ID: b8c7e4715ccd
Revises: f0ca0b73a951
Create Date: 2023-04-30 18:15:58.250873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c7e4715ccd'
down_revision = 'f0ca0b73a951'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('teleg_id', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'teleg_id')
    # ### end Alembic commands ###
