"""5th try

Revision ID: bb6a856fd449
Revises: 8a75d8188eee
Create Date: 2023-05-01 17:52:47.872056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6a856fd449'
down_revision = '8a75d8188eee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
